name: boletim-diario
on: push
jobs:
  delete-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Close Issue
      - uses: peter-evans/close-issue@v2
      - with:
          comment: |
            Issue title must start with 'ABC-'.
            Auto-closing this issue.
    
