on: push
jobs:
  titlePrefixCheck:
    runs-on: ubuntu-latest
    steps:
      - name: Close Issue
        uses: peter-evans/close-issue@v2
        with:
          issue-number: ${{github.event.issue.number - 1 }}
