on: push
jobs:
  titlePrefixCheck:
    runs-on: ubuntu-latest
    steps:
      - name: Close Issue
        uses: peter-evans/close-issue@v2
        env:
          PR_NUMBER: ${{github.event.issue.number}}
        with:
          issue-number: ${{github.event.issue.number}}
