name: boletim-diario
on: push
jobs:
  delete-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Close Issue
        uses: peter-evans/close-issue@v2
        with:
          issue-number: 1
          comment: Auto-closing issue
    
